export const states = [
  {
    label: 'sI',
    isActive: true,
    isInitial: true,
    isFinal: false,
    transitions: [
      { label: '1', isActive: false, transitionAs: 'leftToRight' },
      { label: '2', isActive: false, transitionAs: 'upToDown' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        positions: { line: { top: 138, left: 38 } },
        rotations: { line: 26, label: -26 },
      },
    ],
  },
  {
    label: 'q0',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: 86, left: -228 },
          label: { top: -2, left: 4 },
        },
        rotations: { line: 136, label: -136 },
      },
      { label: '2', isActive: false, transitionAs: 'upToDown' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        positions: { line: { top: 28, left: 78 } },
      },
    ],
  },
  {
    label: 'q1',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '1', isActive: false, transitionAs: 'upToDown' },
      { label: '2', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        positions: { line: { top: 216, left: -340 } },
        rotations: { line: 118, label: -118 },
      },
    ],
  },
  {
    label: 'q2',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 760,
        positions: {
          line: { top: 210, left: -730 },
          label: { top: 2, left: 16 },
        },
        rotations: { line: 147, label: -147 },
      },
      { label: '2', isActive: false, transitionAs: 'upToDown' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 574,
        positions: {
          line: { top: 220, left: -520 },
          label: { top: -36, left: 32 },
        },
        rotations: { line: 136, label: -134 },
      },
      {
        label: 'A',
        isActive: false,
        transitionAs: 'straight',
        width: 386,
        positions: {
          line: { top: 238, left: -192 },
          label: { top: 2, left: 2 },
        },
        rotations: { line: 90, label: -90 },
      },
    ],
  },
  {
    label: 'q3',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '1', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '2',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        positions: {
          line: { top: -98, left: 58 },
          label: { top: -34, left: 127 },
        },
        rotations: { line: -25, label: 25 },
      },
      { label: '5', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'q4',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: -104, left: 54 },
          label: { top: -34, left: 112 },
        },
        rotations: { line: -45, label: 45 },
      },
      { label: '2', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        positions: { line: { top: 28, left: 78 } },
      },
    ],
  },
  {
    label: 'q5',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: -104, left: 54 },
          label: { top: -34, left: 112 },
        },
        rotations: { line: -45, label: 45 },
      },
      {
        label: '2',
        isActive: false,
        transitionAs: 'straight',
        width: 432,
        positions: {
          line: { top: 84, left: -438 },
          label: { top: -6, left: 204 },
        },
        rotations: { line: 154, label: -154 },
      },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: 86, left: -228 },
          label: { top: -2, left: 4 },
        },
        rotations: { line: 136, label: -136 },
      },
    ],
  },
  {
    label: 'q6',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1,2,5',
        isActive: false,
        transitionAs: 'straight',
        width: 430,
        positions: {
          line: { top: 84, left: -438 },
          label: { top: 2, left: 190 },
        },
        rotations: { line: 154, label: -154 },
      },
      {
        label: 'A,B',
        isActive: false,
        transitionAs: 'straight',
        width: 770,
        positions: {
          line: { top: 210, left: -732 },
          label: { top: 1, left: 246 },
        },
        rotations: { line: 147, label: -147 },
      },
      { label: 'C', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'q7',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        positions: {
          line: { top: 28, left: 72 },
          label: { top: 2, left: 2 },
        },
      },
      { label: '2,5', isActive: false, transitionAs: 'leftToRight' },
      { label: 'A', isActive: false, transitionAs: 'upToDown' },
      {
        label: 'B',
        isActive: false,
        transitionAs: 'straight',
        width: 624,
        positions: {
          line: { top: 28, left: 72 },
          label: { top: -4, left: 544 },
        },
      },
    ],
  },
  {
    label: 'q8',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: 'A,B,C',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: 86, left: -228 },
          label: { top: 16, left: 12 },
        },
        rotations: { line: 136, label: -136 },
      },
    ],
  },
  {
    label: 'q9',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '1,2,5', isActive: false, transitionAs: 'rightToLeft' },
      {
        label: 'A,B',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        positions: {
          line: { top: 84, left: -438 },
          label: { top: 2, left: 200 },
        },
        rotations: { line: 154, label: -154 },
      },
      { label: 'C', isActive: false, transitionAs: 'leftToRight' },
    ],
  },
  {
    label: 'st',
    isActive: false,
    isInitial: false,
    isFinal: true,
  },
  {
    label: 'ct',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [
      {
        label: '1,2,5',
        isActive: false,
        transitionAs: 'loop',
      },
    ],
  },
];
