export const states = [
  {
    label: 'sI',
    isActive: true,
    isInitial: true,
    isFinal: false,
    transitions: [
      { label: '0', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: 130, left: 20 },
          label: { top: -40, left: 110 },
        },
        rotations: { line: 45, label: -45 },
      },
      {
        label: '2',
        isActive: false,
        transitionAs: 'straight',
        width: 430,
        positions: {
          line: { top: 247, left: -88 },
          label: { top: 0, left: 200 },
        },
        rotations: { line: 62, label: -62 },
      },
      {
        label: '3',
        isActive: false,
        transitionAs: 'straight',
        width: 660,
        positions: {
          line: { top: 367, left: -219 },
          label: { top: 0, left: 325 },
        },
        rotations: { line: 70, label: -70 },
      },
    ],
  },
  {
    label: 'ta',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [{ label: '0', isActive: false, transitionAs: 'leftToRight' }],
  },
  {
    label: 'tf',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '0', isActive: false, transitionAs: 'rightToLeft' },
      { label: '1', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'q1',
    isActive: true,
    isInitial: false,
    isFinal: false,
    isHidden: true,
  },
  {
    label: '1a',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [{ label: '0', isActive: false, transitionAs: 'leftToRight' }],
  },
  {
    label: '1f',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '0', isActive: false, transitionAs: 'rightToLeft' },
      { label: '1', isActive: false, transitionAs: 'upToDown' },
      { label: '2', isActive: false, transitionAs: 'downToUp' },
    ],
  },
  {
    label: 'q2',
    isActive: true,
    isInitial: false,
    isFinal: false,
    isHidden: true,
  },
  {
    label: '2a',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [{ label: '0', isActive: false, transitionAs: 'leftToRight' }],
  },
  {
    label: '2f',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '0', isActive: false, transitionAs: 'rightToLeft' },
      { label: '1', isActive: false, transitionAs: 'upToDown' },
      { label: '2', isActive: false, transitionAs: 'downToUp' },
    ],
  },
  {
    label: 'q3',
    isActive: true,
    isInitial: false,
    isFinal: false,
    isHidden: true,
  },
  {
    label: '3a',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [{ label: '0', isActive: false, transitionAs: 'leftToRight' }],
  },
  {
    label: '3f',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '0', isActive: false, transitionAs: 'rightToLeft' },
      { label: '2', isActive: false, transitionAs: 'downToUp' },
    ],
  },
];
