export const states = [
  {
    label: 'sI',
    isActive: true,
    isInitial: true,
    isFinal: false,
    transitions: [
      { label: '0', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        positions: {
          line: { top: 130, left: 20 },
          label: { top: 16, left: 12 },
        },
        rotations: { line: 45, label: -45 },
      },
    ],
  },
  {
    label: 'ta',
    isActive: false,
    isInitial: false,
    isFinal: true,
  },
  {
    label: 'tf',
    isActive: false,
    isInitial: false,
    isFinal: false,
  },
  {
    label: 'q1',
    isActive: true,
    isInitial: false,
    isFinal: false,
    isHidden: true,
  },
  {
    label: '1a',
    isActive: false,
    isInitial: false,
    isFinal: true,
  },
  {
    label: '1f',
    isActive: false,
    isInitial: false,
    isFinal: false,
  },
  {
    label: 'q2',
    isActive: true,
    isInitial: false,
    isFinal: false,
    isHidden: true,
  },
  {
    label: '2a',
    isActive: false,
    isInitial: false,
    isFinal: true,
  },
  {
    label: '2f',
    isActive: false,
    isInitial: false,
    isFinal: false,
  },
  {
    label: 'q3',
    isActive: true,
    isInitial: false,
    isFinal: false,
    isHidden: true,
  },
  {
    label: '3a',
    isActive: false,
    isInitial: false,
    isFinal: true,
  },
  {
    label: '3f',
    isActive: false,
    isInitial: false,
    isFinal: false,
  },
];
