export const states = [
  {
    label: 'sI',
    isActive: true,
    isInitial: true,
    isFinal: false,
    transitions: [
      { label: '1', isActive: false, transitionAs: 'leftToRight' },
      { label: '2', isActive: false, transitionAs: 'upToDown' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        position: { top: 130, left: 44 },
        rotate: 28,
      },
    ],
  },
  {
    label: 'q0',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        position: { top: 90, right: 54 },
        rotate: 136,
      },
      { label: '2', isActive: false, transitionAs: 'upToDown' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        position: { top: 28, left: 72 },
      },
    ],
  },
  {
    label: 'q1',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '1', isActive: false, transitionAs: 'upToDown' },
      { label: '2', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        position: { top: 216, left: -340 },
        rotate: 120,
      },
    ],
  },
  {
    label: 'q2',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 760,
        position: { top: 210, left: -720 },
        rotate: 146,
      },
      { label: '2', isActive: false, transitionAs: 'upToDown' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 580,
        position: { top: 216, left: -520 },
        rotate: 134,
      },
      {
        label: 'A',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        position: { top: 240, right: -140 },
        rotate: 90,
      },
    ],
  },
  {
    label: 'q3',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '1,2', isActive: false, transitionAs: 'leftToRight' },
      { label: '5', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'q4',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        position: { bottom: 90, left: 54 },
        rotate: -45,
      },
      { label: '2', isActive: false, transitionAs: 'leftToRight' },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        position: { top: 28, left: 72 },
      },
    ],
  },
  {
    label: 'q5',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        position: { bottom: 90, left: 54 },
        rotate: -45,
      },
      {
        label: '2',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        position: { top: 90, left: -440 },
        rotate: 150,
      },
      {
        label: '5',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        position: { top: 90, right: 54 },
        rotate: 134,
      },
    ],
  },
  {
    label: 'q6',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1,2,5',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        position: { top: 90, left: -440 },
        rotate: 150,
      },
      {
        label: 'A,B',
        isActive: false,
        transitionAs: 'straight',
        width: 760,
        position: { top: 210, left: -720 },
        rotate: 146,
      },
      { label: 'C', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'q7',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: '1',
        isActive: false,
        transitionAs: 'straight',
        width: 380,
        position: { top: 28, left: 72 },
      },
      { label: '2,5', isActive: false, transitionAs: 'leftToRight' },
      { label: 'A', isActive: false, transitionAs: 'upToDown' },
      {
        label: 'B',
        isActive: false,
        transitionAs: 'straight',
        width: 624,
        position: { top: 28, left: 72 },
      },
    ],
  },
  {
    label: 'q8',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      {
        label: 'A,B,C',
        isActive: false,
        transitionAs: 'straight',
        width: 230,
        position: { top: 90, right: 54 },
        rotate: 136,
      },
    ],
  },
  {
    label: 'q9',
    isActive: false,
    isInitial: false,
    isFinal: false,
    transitions: [
      { label: '1,2,5', isActive: false, transitionAs: 'rightToLeft' },
      {
        label: 'A,B',
        isActive: false,
        transitionAs: 'straight',
        width: 440,
        position: { top: 90, left: -440 },
        rotate: 150,
      },
      { label: 'C', isActive: false, transitionAs: 'leftToRight' },
    ],
  },
  {
    label: 'st',
    isActive: false,
    isInitial: false,
    isFinal: true,
  },
  {
    label: 'ct',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [{ label: '1,2,5', isActive: false, transitionAs: 'loop' }],
  },
];
