export const states = [
  {
    label: 'cAsT',
    isActive: true,
    isInitial: false,
    isFinal: true,
    transitions: [
      // { label: 'v1', isActive: false, transitionAs: 'loop' },
      { label: 'v5', isActive: false, transitionAs: 'leftToRight' },
      // { label: 'v5', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'cBsT',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [
      { label: 'v2', isActive: false, transitionAs: 'leftToRight' },
      // { label: 'v1', isActive: false, transitionAs: 'loop' },
      // { label: 'v5', isActive: false, transitionAs: 'leftToRight' },
      { label: 'v1', isActive: false, transitionAs: 'rightToLeft' },
    ],
  },
  {
    label: 'cCsT',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [
      { label: 'v5', isActive: false, transitionAs: 'loop' },
      { label: 'v1', isActive: false, transitionAs: 'rightToLeft' },
      // { label: 'B', isActive: false, transitionAs: 'leftToRight' },
      // { label: 'v5', isActive: false, transitionAs: 'rightToLeft' },
    ],
  },
  {
    label: 'cAcT',
    isActive: true,
    isInitial: false,
    isFinal: true,
    transitions: [
      // { label: 'v1', isActive: false, transitionAs: 'loop' },
      { label: 'v5', isActive: false, transitionAs: 'leftToRight' },
      // { label: 'v5', isActive: false, transitionAs: 'upToDown' },
    ],
  },
  {
    label: 'cBcT',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [
      { label: 'v2', isActive: false, transitionAs: 'leftToRight' },
      // { label: 'v1', isActive: false, transitionAs: 'loop' },
      // { label: 'v5', isActive: false, transitionAs: 'leftToRight' },
      { label: 'v1', isActive: false, transitionAs: 'rightToLeft' },
    ],
  },
  {
    label: 'cCcT',
    isActive: false,
    isInitial: false,
    isFinal: true,
    transitions: [
      { label: 'v5', isActive: false, transitionAs: 'loop' },
      { label: 'v1', isActive: false, transitionAs: 'rightToLeft' },
      // { label: 'B', isActive: false, transitionAs: 'leftToRight' },
      // { label: 'v5', isActive: false, transitionAs: 'rightToLeft' },
    ],
  },
  // {
  //   label: 'cA',
  //   isActive: true,
  //   isInitial: false,
  //   isFinal: true,
  //   transitions: [
  //     // { label: 'v1', isActive: false, transitionAs: 'loop' },
  //     { label: 'v5', isActive: false, transitionAs: 'leftToRight' },
  //     // { label: 'v5', isActive: false, transitionAs: 'upToDown' },
  //   ],
  // },
  // {
  //   label: 'cB',
  //   isActive: false,
  //   isInitial: false,
  //   isFinal: true,
  //   transitions: [
  //     { label: 'v2', isActive: false, transitionAs: 'leftToRight' },
  //     // { label: 'v1', isActive: false, transitionAs: 'loop' },
  //     // { label: 'v5', isActive: false, transitionAs: 'leftToRight' },
  //     { label: 'v1', isActive: false, transitionAs: 'rightToLeft' },
  //   ],
  // },
  // {
  //   label: 'cC',
  //   isActive: false,
  //   isInitial: false,
  //   isFinal: true,
  //   transitions: [
  //     { label: 'v5', isActive: false, transitionAs: 'loop' },
  //     { label: 'v1', isActive: false, transitionAs: 'rightToLeft' },
  //     // { label: 'B', isActive: false, transitionAs: 'leftToRight' },
  //     // { label: 'v5', isActive: false, transitionAs: 'rightToLeft' },
  //   ],
  // },
  // {
  //   label: 'cC',
  //   isActive: false,
  //   isInitial: false,
  //   isFinal: true,
  //   transitions: [
  //     // { label: 'C', isActive: false, transitionAs: 'rightToLeft' },
  //     { label: 'v2', isActive: false, transitionAs: 'downToUp' },
  //   ],
  // },
  // {
  //   label: '4',
  //   isActive: false,
  //   isInitial: false,
  //   isFinal: false,
  //   transitions: [
  //     { label: 'B', isActive: false, transitionAs: 'downToUp' },
  //     { label: 'A', isActive: false, transitionAs: 'leftToRight' },
  //   ],
  // },
  // {
  //   label: '5',
  //   isActive: false,
  //   isInitial: false,
  //   isFinal: false,
  //   transitions: [
  //     { label: 'B', isActive: false, transitionAs: 'rightToLeft' },
  //     { label: 'C', isActive: false, transitionAs: 'leftToRight' },
  //   ],
  // },
  // {
  //   label: '6',
  //   isActive: false,
  //   isInitial: false,
  //   isFinal: true,
  //   transitions: [{ label: 'B', isActive: false, transitionAs: 'rightToLeft' }],
  // },
];
